kind: Deployment
apiVersion: apps/v1
metadata:
  name: parameter-page
  labels:
    app: parameter-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parameter-page
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: parameter-page
    spec:
      containers:
        - name: parameter-page
          image: adregistry.fnal.gov/applications/parameter-page:latest
          ports:
            - containerPort: 80
