apiVersion: v1
kind: Service
metadata:
  name: parameter-page-load-balancer
  labels:
    app: parameter-page
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 38080
  selector:
    app: parameter-page