name: Continuous Integration / Continuous Delivery Workflow for the Parameter Page web application

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  Setup-Build-Test-Dockerize-Push:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checking out source code
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Resolving dependencies
        run: flutter pub get

      - name: Linting
        run: flutter analyze .

      - name: Running unit tests & widget tests
        run: |
          flutter test

      - name: Installing chromedriver (needed for Integration tests)
        uses: nanasess/setup-chromedriver@v1

      - name: Starting chromedriver and executing integration tests
        run: |
          chromedriver --port=4444 &
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server

      - name: Building web application
        run: |
          flutter build web

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: adregistry.fnal.gov/applications/parameter-page
          tags: |
            # This is the default tag for the last commit of the default branch
            type=edge
            # This is used on a push event and requires a valid semver Git tag
            type=semver,pattern={{version}}
            # This tags PRs with the PR number. E.g., refs/pull/2/merge -> pr-2
            type=ref,event=pr
            # This sets the latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AD Registry, Harbor
        uses: docker/login-action@v2
        with:
          registry: adregistry.fnal.gov
          username: ${{ secrets.ADREGISTRY_USERNAME }}
          password: ${{ secrets.ADREGISTRY_SECRET }}

      - name: Building Docker image and pushing to adregistry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
