name: Parameter page mock

on:
  workflow_dispatch:

jobs:

  Build-Dockerize-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out source code
        uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-install-cache

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Resolving dependencies
        run: flutter pub get
      - name: Building web application
        run: |
          flutter build web --dart-define=USE_MOCK_SERVICES=true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: adregistry.fnal.gov/applications/parameter-page
          tags: |
            type=raw,value=mock

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AD Registry, Harbor
        uses: docker/login-action@v2
        with:
          registry: adregistry.fnal.gov
          username: ${{ secrets.ADREGISTRY_USERNAME }}
          password: ${{ secrets.ADREGISTRY_SECRET }}

      - name: Building Docker image and pushing to adregistry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
